# Cloudflare Pages configuration
name = "johnifier"
compatibility_date = "2024-01-01"

[build]
command = "npm run build:demo"
cwd = ""
watch_dir = "demo"

[build.upload]
format = "service-worker"
dir = "dist/demo"
